thesofproject/rimage

- .travis.yml
Enable simple build test for rimage.
Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>
> CI: Travis: init build test for rimage

- src/ext_manifest.c
- src/manifest.c
This part of binary should contain valid firmware version.
> manifest: ads: meu: Fill FW version description also when MEU is used

- src/adsp_config.c
- src/rimage.c
Build test: https://github.com/thesofproject/sof/pull/3425
> toml: Fix adsp v1.5 parsing

- .travis.yml
CI build system should be more restrictive.
> Add more warnings to make command, treat warnings as errors

- src/adsp_config.c
- src/elf.c
- src/manifest.c
- src/rimage.c
> Fix a couple crashes

- src/adsp_config.c
Improve code readability and allow to easily expand parsers list in future.
> Keep available manifest parsers in list, move config version parsing to separate function

- config/kbl.toml
- config/skl.toml
change image_size to the real SRAM size
> Image size update for SKL/KBL

- README.md
> README.md: explain how to run SOF tests on rimage work in progress

- src/pkcs1_5.c
Refactor the signing and verification functions as they have a lot of
duplicated code and adding openssl 3.0 support without refactor would
make things even more messy.
1) Add common "rimage_read_key" to read the key from file.
2) Variate most important functionality based on different openssl versions:
- rimage_check_key
- rimage_set_modexp
- rimage_sign
- rimage_verify
- rimage_get_key_size
> rimage: refactor and add openssl 3.0 support

- config/mt8186.toml
Add mt8186.toml to support sof-mt8186.ri binary build
Signed-off-by: Allen-KH Cheng <Allen-KH.Cheng@mediatek.com>
Signed-off-by: Tinghan Shen <tinghan.shen@mediatek.com>
--
related to sof PR https://github.com/thesofproject/sof/pull/5239
> config: Add mt8186.toml

- config/mtl.toml
Add MicSel config int mtl.toml
Prepare for MicSel support in SOF FW.
> mtl: add MicSel support

- config/mtl.toml
Add KD and KPB module configs to the manifest
> mtl: config: add kd and kpb modules

- src/manifest.c
- src/rimage.c
Fixes errors which came out after static analysis.
> Fix of resource releasing and returning of a error codes

- src/manifest.c
> manifest: fix goto order in verify_image

- config/mt8188.toml
Add mt8188.toml to support sof-mt8188.ri binary build.
Signed-off-by: Tinghan Shen <tinghan.shen@mediatek.com>
> config: Add mt8188.toml

- config/tgl-cavs.toml
This patch adds module config iir eq module.
Signed-off-by: Jaska Uimonen <jaska.uimonen@intel.com>
> config: tgl-cavs: add iir and fir eq module config

- src/elf.c
We don't send ROM data to the DSP so there's no need to convert ROM addresses to cached aliases. Doing so breaks calculations with IPC4 XTOS builds.
> Don't convert ROM addresses to cached aliases

- config/mtl.toml
- config/tgl-cavs.toml
Add KPB, Selector and KD module config
Signed-off-by: Libin Yang <libin.yang@intel.com>
> config: tgl-cavs: add kpb, selector and kd support

- config/tgl-h-cavs.toml
Update the list of modules to match that of "tgl-cavs".
> config: tgl-h-cavs: align modules to tgl-cavs config

- config/mtl.toml
Change of uuid
regarding Windows compatibility
> kpb: update UUID

- README.md
Fixes commit 77d4a2acd751 ("cmake: remove "install" target")
> README.md: remove "install" target

- config/vangogh.toml
Add vangogh toml file to support sof-vangogh.ri binary build
> config: add vangogh toml file to support vangogh build

- config/lnl.toml
- config/mtl.toml
- config/tgl-cavs.toml
- config/tgl-h-cavs.toml
This patch enables load the of Time domain fixed beamformer (TDFB).
> Congfig: Add TDFB to TGL, TGL-H, MTL, and LNL
