thesofproject/rimage

src/file_simple.c, src/include/rimage/rimage.h, src/rimage.c
i.MX8X is very similar with i.MX8. Memory layout is the same
except IRQSTEER address.
Code will be shared but there will be different firmware binaries
named:
* sof-imx8.ri, for i.MX8
* sof-imx8x.ri, for i.MX8X
Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
=> rimage: Add support for i.MX8X

src/elf.c, src/include/rimage/rimage.h, src/manifest.c
Unused arguments shouldn't be passed to function because it
makes code messy.
=> Remove unused 'image' argument in elf_find_section()

LICENSE
This changes the LICENSE file to match the LICENSE file
from the main SOF repo, except they entries for the kconfig
scripts which are not here in this repo.
Signed-off-by: Daniel Leung <danielcp@gmail.com>
=> Match LICENSE from the main SOF repo

src/elf.c
Fixes following error when compiling code:
...
src/elf.c: In function ‘elf_find_section’:
src/elf.c:469:20: error: initialization discards ‘const’ qualifier
from pointer target type [-Werror=discarded-qualifiers]
469 |  Elf32_Ehdr *hdr = &module->hdr;
|                    ^
cc1: all warnings being treated as errors
...
=> Fix compiler errors

src/elf.c, src/manifest.c
Fixes Zephyr crashes in C++ tests with static constructors put in .init_array section.
=> Fix init_array section not copied to ri image

CMakeLists.txt, src/elf.c, src/ext_manifest.c, src/include/rimage/rimage.h, src/include/sof/kernel/ext_manifest.h, src/include/sof/kernel/ext_manifest_gen.h, src/rimage.c
ext_man: Create extended manifest
Extended manifest is a place to store metadata about firmware, known during
compilation time - for example firmware version or used compiler.
Given information are read on host side before firmware startup.
This part of output binary is not signed.
extracted from https://github.com/thesofproject/sof/pull/2427
=> ext_man: Create extended manifest

src/elf.c, src/ext_manifest.c, src/include/rimage/rimage.h, src/include/sof/kernel/ext_manifest_gen.h, src/rimage.c
https://github.com/thesofproject/rimage/issues/12
Know logs for case when ext_mnf is not present loooks like:
```
warning: can't find section .fw_metadata in module /mnt/c/projects/sof_kt/build/sof-cnl
warning: unable to write extended manifest, -125
```
instead of:
```
warning: can't find section .fw_metadata in module /home/lrg/work/zephyrproject/zephyr/build/zephyr/zephyr.elf.mod
error: section .fw_metadata can't be found
error: failed to read .fw_metadata section content, code -22
warning: unable to write extended manifest, -22
```
For case with ext_man, there is no any difference in logs
=> Ext mnf optional

src/elf.c, src/manifest.c
without this changes build for TGL fail.
Description: https://github.com/thesofproject/sof/pull/2086#issuecomment-625750655
=> LMA: Add changes from FW repo

CMakeLists.txt, src/rimage.c
See commit messages.
This makes the write_firmware NULL pointer added by commit
dd77445 and corresponding crash more user-friendly.
Before:
```
Program received signal SIGSEGV, Segmentation fault.
```
After:
```
rimage: src/rimage.c:197: main: Assertion `image.adsp->write_firmware'
failed.
```
=> Default CMAKE_BUILD_TYPE to Debug, add assert() for NULL pointer

src/include/rimage/sof/user/manifest.h
This feature is not used by SOF anyway and only causes
FW load failures, we can set it to 0xffff so it will
work for ADL+ platforms.
Signed-off-by: Janusz Jankowski <janusz.jankowski@linux.intel.com>
=> manifest: set feature mask to 0xffff

src/adsp_config.c
Error codes like ENOKEY and EBADE are not provide for all windows
toolchains, so to immit possible build errors, some more standard
error codes should be used.
Detailed error message is printed in stderr, so end user still
will be well informed about error source.
=> toml: Use only standard error codes

src/manifest.c
Does not solve https://github.com/thesofproject/sof/issues/3423 but
converts a buffer overflow and crash into a more usable assert.
Buffer overflow found by running rimage with valgrind and the binaries
provided by @singalsu
=> manifest.c: assert buffer overflow in man_copy_sram()

src/pkcs1_5.c
v2: as requested by @ktrzcinx , I also cleaned up the code a bit. Now there are 2 commits:
- 1st commit changes the entire source of these functions but does not change the rimage compiled binary
- 2nd commit is the actual fix with just a one-line change in each function
v1:
Found by chance and reproduced by making a typo in the key's filename.
Note there is already an (unchanged) error message:
```
pkcs: signing with key sof/keys/otc_private_key_3k.pemX
error: can't open file sof/keys/otc_private_key_3k.pemX -2
Firmware manifest and signing completed !
```
But now rimage does not pretend success and the build does not keep
going with an unsigned image like nothing happened.
=> pkcs1_5.c: don't pretend everything is fine when failing to sign

.gitignore
Any generated file should be tracked by git to keep repositiry clean.
Such an file should be added to .gitignore to reduce possibility of
accidentally pushig this file to remote branches, eg. after typing
`git add *` before pushing changes.
=> gitignore: Add checkpatch temporary file to gitignore

src/cse.c
Add simple crc32 function to calculate the checksum for v2.5 headers.
Implementation is very simple using shift register as we don't require
speed. Calculate the v2.5 header checksum with crc-32/iso-hdlc
parameters.
=> cse: add simple crc32 function to calculate the v2.5 header checksum

README.md
Also show useful "make help" that lists all targets.
Show -B option of CMake that avoids changing the current directory to
the build directory: especially inconvenient considering the
recommended, CMake way to clean is to delete this directory and the
recommended way to build multiple configurations is to use multiple
build directories.
-B was introduced in CMake 3.13 which has been released two years ago
now and CMake spoils its users with a choice of ways to upgrade:
https://cmake.org/download/
https://apt.kitware.com/
https://pypi.org/project/cmake/
This does _not_ imply CMakeLists.txt should drop backward compatibility
with CMake < 3.13. I only think a README.md file should not keep the
majority of users in the dark only for the convenience of a minority of
obsolete CMake users. …
=> README: install is optional and missed "sudo". CMake 3.13 -B option.

config/tgl.toml, src/adsp_config.c, src/cse.c, src/css.c, src/hash.c, src/include/rimage/cse.h, src/include/rimage/css.h, src/include/rimage/manifest.h, src/include/rimage/plat_auth.h, src/include/rimage/rimage.h, src/include/rimage/sof/user/manifest.h, src/manifest.c, src/pkcs1_5.c, src/plat_auth.c, src/rimage.c
This PR will add signing support for CAVS2.5 platforms. Key differences are hashes are now SHA384 and signing is now RSA PSS. This is a plan B until meu can be released.
TODO:
=> rimage signing support for CAVS2.5

src/pkcs1_5.c
This comment is meant for "git grep salt", that's its main purpose.
Much more obvious timestamps aside, this new code is the only
non-deterministic part of rimage - learned the very hard way
(OpenSSL "documentation" calls it "sLen"...)
A/B testing of build system changes is much, much easier when
locally and temporarily making the build 100% deterministic.
=> pkcs_v1_5_sign_man_v2_5(): add "salt length" comment

src/rimage.c
It wasn't exactly obvious who does what.
=> minor -h fix: -s meu_offset disables rimage signing

src/ext_manifest.c
sec_buffer is allocated inside elf_read_section() and as local
variable it's deleted after ext_man_build() exit, so free()
should be called here.
=> ext_man: Fix memory leak after manifest build

src/ext_manifest.c
sec_buffer allocated inside elf_read_section()
was not being freed before and is freed now.
=> Ext man fix mem leak

src/adsp_config.c
'key' argument must describe 'key' which triggered error message
to keep stderr output helpfull.
=> config: Fix 'module' parsing error messages

src/adsp_config.c
Issue detected by Klocwork
Signed-off-by: Slawomir Blauciak <slawomir.blauciak@linux.intel.com>
=> [Klocwork] Sanity check allocated memory

config/apl.toml, config/cnl.toml, config/icl.toml, config/jsl.toml, config/tgl-h.toml, config/tgl.toml
We have 46 bank HP and 1 bank LP SRAM on TGL, change to toml config file
to reflect that.
We have 30 bank HP and 1 bank LP SRAM on TGL-H, change to toml config file
to reflect that.
=> correct Image size for cAVS platforms

config/tgl-cavs.toml
Apply "config: tgl: change image_size to the real SRAM size"
(9e50a02f1b) to tgl-cavs
Signed-off-by: Rander Wang <rander.wang@intel.com>
=> config: tgl-cavs: change image_size to the real SRAM size

config/sue.toml
We have 47 bank HP and 1 bank LP SRAM on Suecreek, change the toml config file
to reflect that.
Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>
=> config: sue: change image_size to the real SRAM size

config/rn.toml
Add rn toml file to support sof-rn.ri binary build
Signed-off-by: Basavaraj Hiregoudar <basavaraj.hiregoudar@amd.com>
Signed-off-by: Anup Kulkarni <anup.kulkarni@amd.com>
Signed-off-by: balapati <balakishore.pati@amd.com>
=> config: add rn toml file to support renoir build

src/pkcs1_5.c
It seems that the manifest header is not included for signing (fw_image_manifest_v1_5).
If we are including the header then at least the data1 to be pointed to,
`char *const data1 = (char *)man;`
But in the code, the offset added is MAN_CSS_MAN_SIZE_V1_5 which is 174 (The fw_image_manifest_v1_5 size in words).
`char *const data1 = (char *)man + MAN_CSS_MAN_SIZE_V1_5;`
So, here the offset for data1 can be,
1) 0 (if fw_image_manifest_v1_5 header is included for signing)
2) 696 (which is sizeof(struct fw_image_manifest_v1_5) if header is not included for signing)
It is neither 0 nor 696 but 174 which is the fw_image_manifest_v1_5 size in words.
Moreover, the size that is passed to pkcs_v1_5_sign_man_v1_5 function is,
`unsigned const size1 = image->image_end - sizeof(*man);`
We are …
=> fixing incorrect data offset in ri_manifest_sign_v1_5

config/apl.toml, config/bdw.toml, config/bsw.toml, config/byt.toml, config/cht.toml, config/cnl.toml, config/hsw.toml, config/icl.toml, config/imx8.toml, config/imx8m.toml, config/imx8ulp.toml, config/imx8x.toml, config/jsl.toml, config/kbl.toml, config/mt8195.toml, config/rn.toml, config/skl.toml, config/sue.toml, config/tgl-cavs.toml, config/tgl-h.toml, config/tgl.toml, src/adsp_config.c, src/include/rimage/rimage.h
This enum value is used only to distinguish suecreek from other
platforms, which can be done also by platform name.
Manual enumeration, in separate toml files with manual synchronization
in enum definition is quite error prone. After commit
9bf46d3: "rimage: Add support for mt8195" and
9716e10: "config: Add imx8ulp.toml" there are two different
platform with the same enum value 15 specified, which proves such a
thesis.
=> config: Remove machine_id enum

src/adsp_config.c
Function with `parse_uint32` should return uint32_t value
Signed-off-by: Karol Trzcinski <karolx.trzcinski@intel.com>
=> config: Adjust return type with function name

src/rimage.c
Message should reflect error root cause.
=> rimage: Fix error message content after adsp malloc fail

src/pkcs1_5.c
This makes is more obvious when the filename is empty, which happened in
bug https://github.com/thesofproject/sof/pull/4711
Also prefix identical log statements with their different `__func__`
names.
=> pkcs: quote the name of key file when logging it

src/include/rimage/sof/kernel/ext_manifest.h
This patch changes the incorrect signature of extended manifest
to the correct one "$AE1"
Signed-off-by: Marcin Rajwa <marcin.rajwa@linux.intel.com>
=> ext_manifest: Fix incorrect signature

src/include/rimage/rimage.h, src/manifest.c, src/rimage.c
This patch removes the unnecessary and unscalable -x option.
This option aims to add an offset to the .data section of
its parent .module section. This is horrible idea because this
offset will vary depend on the compiler used. It is better and
much easier to just store only the .data section so the offset
is always 0.
SoF FW related change -> https://github.com/thesofproject/sof/pull/4762
Signed-off-by: Marcin Rajwa <marcin.rajwa@linux.intel.com>
=> remove '-x' option

src/rimage.c
When some automation script gets some rimage flag wrong then rimage
exits and does not run at all. In such a case we want the build to fail
immediately and see the error at the bottom of the build logs and not
obscured by other, consecutive failures caused by the lack of rimage
output.
Take control of the exit code away from usage() and give it back to
main() where it belongs.
=> Do not exit(0) on invalid options or parameters

src/include/rimage/sof/kernel/ext_manifest.h
This reverts commit 241af313dab49db06d6e6f0af3330f1a916de664 so the DSP
can boot again.
On my APL UP2 this fixes:
```
10:06:38: 00:0e.0: unstall/run core: core_mask = 1
10:06:38: 00:0e.0: DSP core(s) enabled? 1 : core_mask 1
10:06:38: 00:0e.0: FW Poll Status: reg[0x4c]=0x40000000 successful
10:06:38: 00:0e.0: FW Poll Status: reg[0x4]=0x3030202 successful
10:06:38: 00:0e.0: FW Poll Status: reg[0x4]=0x1010202 successful
10:06:38: 00:0e.0: DSP core(s) enabled? 0 : core_mask 2
10:06:38: 00:0e.0: FW Poll Status: reg[0x80000]=0x5000001 successful
10:06:41: 00:0e.0: FW Poll Status: reg[0x80000]=0x80000007 timedout
10:06:41: 00:0e.0: error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
10:06:41: 00:0e.0: FW Poll Status: reg[0x160]=0x140000 successful
10:06:41: 00:0e.0: ------------[ DSP …
```
=> Revert "ext_manifest: Fix incorrect signature"

README.md
Otherwise the SHA1 is not found and the rest of the process fails.
Problem discovered in
https://github.com/thesofproject/sof/pull/4790#discussion_r713326709
=> README.md: add warning that forks must be created using Github

src/css.c
This is useful to show which one of the 3 duplicated functions runs.
=> css.c: add __func__  to "completing manifest" log

src/include/rimage/rimage.h, src/manifest.c, src/pkcs1_5.c, src/rimage.c
Add function to resign already signed images. This can
be done with switch "q" as follows:
"rimage -q sof-tgl.ri -o sof-tgl-mod.ri -c tgl.toml -k key.pem"
=> [RFC] rimage: add functionality to resign fw image

src/manifest.c
Set buffer to NULL to prevent freeing bogus memory in error case.
=> manifest: fix buffer init in resign

src/rimage.c
x param was removed from switch case but not from getopt. So if you use
x rimage silently fails on the switch case.
Signed-off-by: Curtis Malainey <cujomalainey@chromium.org>
=> remove x from getopt

src/cse.c
literals are signed by default, so shifting them 32 times is an
overflow, found via cppcheck
Signed-off-by: Curtis Malainey <cujomalainey@chromium.org>
=> cse: fix signed integer overflow

src/pkcs1_5.c
cppcheck gives errors from openssl 1.0 related code that has some old
churn and should be fixed, so fix it.
=> rimage: fix openssl 1.0 support

src/adsp_config.c
This patch fixes an invalid format specifier that causes a numeric value
to be interpreted as a string, resulting in an Segmentation fault.
=> adsp_config: fix invalid format specifier

CMakeLists.txt
Update to C99 standard to match SOF. Silenced warning generated by newer GCC compilers related to int cast of char typed values that may result in negative values. Analyzed the code where warning occurs. Values typed char where warning is shown are passed to C standard isdigit function that handles cases when char returns negative value as int so no harm done.
Syntax fix in CMake function target_link_libraries - linkage of crypto library to more generic approach.
In CMake documentation adding a library should look like this. When compiler other than GCC is used other (matching that compiler) linker flag is generated.
=> Update to C99 standard to match SOF. Silenced warning generated by newer gcc versions

src/adsp_config.c
2 commits. Main one:
Fix confusion in headers between uint8_t arrays and strings 
Strings are null terminated, byte arrays not always.
Fixes garbage in debug output issue #86
Change parse_str_key() argument from char * to uint8_t *. Casting the
argument on almost every call was a clear indication of the problem.
Add new DUMP_PRINTABLE_BYTES() to printf uint8_t arrays _and_ their
_optional_ padding.
No change to the .ri output, bit for bit identical.
Here's an example of how the -v output is fixed:
```diff
mem_zone.host_offset: 0x0
cse
-         partition_name: 'ADSPADSP.man'
+         partition_name: ADSP
header_version: 1
entry_version: 1
nb_entries: 3
-             entry.name: 'ADSP.man'
+             entry.name: ADSP.man\x00\x00\x00\x00
entry.offset: 0x58
entry.length: 0x378
- …
```
=> Fix confusion in headers between uint8_t arrays and strings

CMakeLists.txt, src/manifest.c
Two commits:
1) Added handling of OpenSSL on Windows using OPENSSL_PATH.
Upgraded CMake minimal version to 3.20.0 to match Zephyr and to use cmake_path freely.
2) Fixed warning treated as error in src/manifest.c where variable passed to fprintf was of type size_t and expected format of long int.
Signed-off-by: Andrey Borisovich [andrey.borisovich@intel.com](mailto:andrey.borisovich@intel.com)
=> Resurrect Windows build and upgrade CMake version to match Zephyr

src/include/rimage/sof/user/manifest.h
External libraries can contain processing module code or common library code.
Library manager need to distinguish between both type of modules for proper loading.
Signed-off-by: Jaroslaw Stelter <jaroslaw.stelter@intel.com>
=> Add lib_code module type.

config/mtl.toml
Added Up Down Mixer module to config/mtl.toml
Increased modules count.
Signed-off-by: Arsen Eloglian <ArsenX.Eloglian@intel.com>
=> mtl: Add UPDWMIX module to the manifest

src/manifest.c
Pass fw_ver_micro value to ace_v1_5 manifest.
Signed-off-by: Damian Nikodem <damian.nikodem@intel.com>
=> manifest: add fw_ver_micro to manifest

src/include/rimage/rimage.h, src/pkcs1_5.c
Ace signing is currently missing openssl3 support, so add it
Signed-off-by: Jaska Uimonen <jaska.uimonen@intel.com>
=> rimage: make ace15 signing to use cavs25 functions

config/mtl.toml
No mux in the manifest
Signed-off-by: Kwasowiec, Fabiola <fabiola.kwasowiec@intel.com>
=> mux: add mux cfg to list of modules

config/mtl.toml
error: invalid type /error: key 'module' parsing error
Signed-off-by: Kwasowiec, Fabiola <fabiola.kwasowiec@intel.com>
=> mux: fix module type

config/mtl.toml
error: invalid type 16error: key 'module' parsing error probe module type is 10,which is treated hexally
Signed-off-by: Kwasowiec, Fabiola <fabiola.kwasowiec@intel.com>
=> probe: mtl.toml invaliv probe type

config/tgl-cavs.toml
This patch adds module config for smart_amp.
Signed-off-by: Chao Song <chao.song@linux.intel.com>
=> config: tgl-cavs: add smart_amp module config

src/adsp_config.c, src/include/rimage/adsp_config.h, src/include/rimage/rimage.h, src/rimage.c
Add a '-p' command line flag to set Intel reserved bit in IMR area.
Inspired by #113 but unfortunately this is urgent and has to be done with a command line switch, so I had to guess what this should do.
=> Add a command line option to set production bit

config/mtl.toml
This patch adds smart amp test module config for mtl.
Signed-off-by: Chao Song <chao.song@linux.intel.com>
=> config: mtl: add smart amp test module config

config/tgl-cavs.toml, src/adsp_config.c, src/elf.c, src/include/rimage/rimage.h
Rimage calculates sizes of ELF sections, for which it has to use addresses from the same address space: either all cached or all uncached. The ELF image itself can contain mixed addresses. Convert all to cached for internal calculations.
=> Convert all ELF addresses to cached for calculations

config/mtl.toml, config/tgl-cavs.toml, src/adsp_config.c, src/include/rimage/sof/user/manifest.h
USe some reverved bits to add the init config information for modules that will be used to indicate whether the base config extension needs to be added to the init module payload or not.
=> Add Init config type for modules

config/mtl.toml, config/tgl-h-cavs.toml, config/tgl-h.toml, config/tgl.toml, src/adsp_config.c
A recent commit ec649f37d661 ("Convert all ELF addresses to cached for calculations") had a bug: it assumed a call to parse_uint32_hex_key() for an absent key would return an error by default, which isn't the case. To force it set the default return code to an error value.
=> Fix regression - make default return code an error

config/tgl-h.toml, config/tgl.toml
tgl.toml and tgl-h.toml are only used for xtos builds.
Suggested-by: Guennadi Liakhovetski <guennadi.liakhovetski@linux.intel.com>
Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>
=> config:tgl/tglh: Do not set cached/uncached address aliases

src/adsp_config.c
Improvement and bug fix for https://github.com/thesofproject/rimage/pull/130
=> Improvement for init_config parsing

config/mtl.toml
The micsel module will use base config extension,
init_config should be one for it.
=> config: mtl: set init_config for micsel

src/rimage.c
In image re-signing mode or if there are no input files, the memory allocated for heap_adsp was not released.
=> main: heap_adsp release fix

CMakeLists.txt, src/elf.c, src/ext_manifest.c, src/file_simple.c, src/file_utils.c, src/include/rimage/file_utils.h, src/include/rimage/rimage.h, src/manifest.c
A new function create_file_name has been created that prepares the name of the output file with the given extensions. Unlike the previous solution, it checks whether the new name will fit in the output buffer.
A new file_utils.c file has been prepared, into which generic functions to simplify the use of files will be moved.
Added a new get_file_size function which allows to conveniently get the size of the file.
Simplified retrieval of file size by using the function get_file_size in manifest and elf.
=> file_utils: manifest: elf: Separation of the code fragments to the new functions

config/mtl.toml, config/tgl-cavs.toml
Module type is interpreted as hex number
=> rimage: use hex number

src/toml_utils.c
Modified the `strtoul` function parameter to automatically recognize the value format. This will avoid the situation when a decimal  value is parsed as hexadecimal.
=> toml_utils: Adding support for decimal numbers in hex parser

config/mtl.toml
Port from tgl-cavs.toml
fixes bug : https://github.com/thesofproject/sof/issues/7204 ([BUG] missing IIR EQ module config in rimage for MTL)
=> mtl: add eq-iir and fir support

src/css.c, src/pkcs1_5.c
Recent changes introduce build error, fix the build error.
=> rimage: fix build error

config/mtl.toml
Add ARIA module to MTL extended manifest.
=> mtl: add Aria module to extended manifest

src/adsp_config.c, src/ext_manifest.c, src/file_simple.c, src/file_utils.c, src/include/rimage/file_utils.h, src/manifest.c, src/pkcs1_5.c, src/rimage.c
Added a generic function that displays a file operation error message.
Removed duplicated function descriptions - functions are already described in the header file.
Use file_error function to print file related errors.
Fixed minor issues.
=> file_utils: Add file_error function

config/tgl-h.toml, config/tgl.toml
Now that rimage can distinguish between Zephyr and XTOS builds, we can use memory alias specifiers with both.
This reverts commit 1e0a85b44a19db37f9dd18906091d87abd8bd5e6.
=> Revert "config:tgl/tglh: Do not set cached/uncached address aliases"

config/apl.toml, config/cnl.toml, config/icl.toml, config/jsl.toml, config/kbl.toml, config/skl.toml, config/sue.toml
cAVS 1.5, 1.8 and 2.0 are supported by Zephyr, their configurations need alias definitions.
=> cAVS: add alias definitions to cAVS 1.5-2.0

src/adsp_config.c, src/elf.c, src/ext_manifest.c, src/file_simple.c, src/include/rimage/elf.h, src/include/rimage/manifest.h, src/include/rimage/misc_utils.h, src/include/rimage/rimage.h, src/include/rimage/sof/user/manifest.h, src/manifest.c, src/misc_utils.c, src/rimage.c
* Added header guard in elf.h file to allow safe include this header by multiple units.
* The man create modules function may return an error that was ignored. Added check of a return value.
* There was no dram_offset value in any configuration file. It also wasn't used anywhere in the code. So the code reading it from the tolm file has been removed.
* Added functions to print enum and flags value. Added name_val structure representing name/value tuple. Added function
print_enum which displays the name of the enum corresponding to a given value. Added print_flags function which display names of flags constituting a given value.
* Create new memory_config structure. Moved mem_zone field from adsp structure to the new memory_config structure
* Moved memory alias configuration to a new …
=> Set of small changes to improve code readability and fix bugs (SP2)

src/manifest.c, src/rimage.c
Some platforms (eg. tgl) dont have modules configuration in a toml files. An attempt to use the configuration template ended with a reference to a null pointer. This commit fixes this issue.
=> [FIX] Fix for manifest: Use module manifest from toml as a template for elf modules

CMakeLists.txt
The deleted "install" target copied only the rimage executable and left the config files behind. This gave the wrong impression that the executable is useful without config files.
"Installing" also gave the wrong impression that rimage versions are somewhat stable and relatively independent of SOF versions: they're not. In fact there is no such thing as an rimage "version": everyone should always use the exact rimage _git commit_ from the west manifest or git submodule. There are no rimage "releases" and no semantic versioning or anything like it, rimage is effectively part of the SOF source and build and run directly from its build directory by practically every SOF developer and SOF CI thanks to
```
sof/src/arch/xtensa/CMakeLists.txt#ExternalProject_Add(rimage_ep ... …
```
=> cmake: remove "install" target

src/file_simple.c
The original size given to the "calloc" call did not account for the necessity to pad section sizes to a multiple of 4 bytes. As such, every time we wrote a section that did not have a size multiple of 4 we would overflow the allocated buffer.
Fix the calloc call to account for that padding requirement.
=> file_simple: Allocate correct buffer size for writing sections out

config/lnl.toml
Change of uuid
regarding Windows compatibility.
It was already changed for MTL, but need to be updated also for LNL.
Signed-off-by: Jaroslaw Stelter <Jaroslaw.Stelter@intel.com>
=> kpb: update kpb uuid for lnl

config/tgl-cavs.toml, config/tgl-h-cavs.toml
This patch adds Aria module for TGL and TGL-H platforms. The used configuration data is copy from mtl.toml. This change allows to use Aria component in topologies.
=> Config: Add Aria module to tgl-cavs.toml and tgl-h-cavs.toml

src/rimage.c
Fixes commit 6e3abe6afed3 ("rimage: Add suport for loadable modules")
It looks like that commit mistook the `:` sign as a separator. This accidentally added the requirement to give `-p` a parameter which is then ignored. Remove the spurious `:`.
=> rimage.c: fix bug where -p requires a new and ignored parameter

config/tgl-cavs.toml, config/tgl-h-cavs.toml
The configuration is for now copy from IIR, name and UUID are changed. The init_config is set to 1 to let kernel know that the base_cfg_ext is passed to firmware.
=> Config: Add crossover component for TGL and TGL-H cAVS platforms

config/lnl.toml, config/mtl.toml
The ADSP.man contents is different for ACE_V1_5 layout compared to CAVS_V2_5 layout. so the ADSP.man length should be adjusted accordingly.
With this fix, sof_ri_info.py can be used to analyze LNL and MTL firmware images created with rimage.
Closes: https://github.com/thesofproject/sof/issues/8073
=> config: lnl+mtl: fix length of ADSP.man CSE manifest

config/lnl.toml, config/mtl.toml
This PR adds the crossover component for MTL and LNL. The parameters are copied from TGL and TGL-H configuration of crossover.
=> Config: Add crossover component for MTL and LNL platforms

config/lnl.toml, config/mtl.toml, config/tgl-cavs.toml, config/tgl-h-cavs.toml
This patch enables load of the DC blocker component.
=> Config: Add DCblock to TGL, TGL-H, MTL, and LNL

config/mtl.toml
Smart amp will be a loadable module.
It is only for mtl-006-stable branch. Since rimage was integrated into sof, this change will not affect main branch.
=> mtl: remove smart amp config in basefw

CMakeLists.txt
Gently redirect users to
https://github.com/thesofproject/sof/tree/main/tools/rimage and https://github.com/thesofproject/sof/issues/8178
=> cmake: block compilation of the 'main' rimage branch

README.md
Also warn that the main branch is now frozen.
=> README.md: show how to git cherry-pick across sof.git and rimage.git

config/lnl.toml
Fixes commit fbea59358d06 ("rimage: mtl: fix key slot setup based on imr type") which broke LNL compilation like this:
```
error: 1 unparsed keys left in 'signed_pkg'
error: key 'signed_pkg' parsing error
```
Of course LNL is never going to be released on this stable-v2.7 branch but this one-line fix is just the smallest and simplest fix to keep everything building and green. It also keeps everything simple and consistent.
This commit does not change the final image (compared to before rimage commit fbea59358d06) because the default value is now 0x20 + IMR type.
Fixes are normally submitted to the main branch first and then cherry picked to stable branches. However fbea59358d06 has been made in stable-v2.7 first so make this change also in stable-v2.7 first for consistency.
=> [stable-v2.7] config/lnl.toml: drop now invalid signed_pkg.partition_usage
